# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "AI Facebook Ads Pro"
handle = "ai-facebook-ads-pro"
client_id = "9628dd612d6d4220f99fd05cd5c37c21"
application_url = "https://facebook-ai-ads-shopify.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "volter-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders,read_customers,read_customer_events"

[auth]
redirect_urls = [
  "https://facebook-ai-ads-shopify.vercel.app/auth/shopify/callback",
  "https://facebook-ai-ads-shopify.vercel.app/auth/callback"
]

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks"

[[webhooks.subscriptions]]
topics = ["customers/data_request"]
uri = "/webhooks"

[[webhooks.subscriptions]]
topics = ["customers/redact"]
uri = "/webhooks"

[[webhooks.subscriptions]]
topics = ["shop/redact"]
uri = "/webhooks"

[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "/webhooks"

[[webhooks.subscriptions]]
topics = ["orders/updated"]
uri = "/webhooks"

[[webhooks.subscriptions]]
topics = ["products/create"]
uri = "/webhooks"

[[webhooks.subscriptions]]
topics = ["products/update"]
uri = "/webhooks"

[pos]
embedded = false